---
name: pre-commit
on:
  pull_request:
  push:
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update
      - uses: actions/checkout@v4
      - run: python -m pip install pre-commit
      - uses: actions/cache/restore@v3
        with:
          path: ~/.cache/pre-commit/
          key: pre-commit-4|${{ env.pythonLocation }}
            |${{ hashFiles('.pre-commit-config.yaml') }}
      - run: pre-commit run --show-diff-on-failure --color=always --all-files
      - uses: actions/cache/save@v3
        if: ${{ always() }}
        with:
          path: ~/.cache/pre-commit/
          key: pre-commit-4|${{ env.pythonLocation }}
            |${{ hashFiles('.pre-commit-config.yaml') }}
